#!/bin/bash

cd $PWD
mkdir ${1:-new-node}
cd ${1:-new-node}

npm init -y

mkdir src
cd src

mkdir api entities repositories router services utils

touch utils/env-wrapper.ts
touch router/router.ts
touch app.ts
touch status-codes.ts

cd ..

touch ormconfig.ts
touch main.ts
touch .gitignore
touch ./.env
touch tsconfig.json

FILE="./ormconfig.ts"

/bin/cat <<EOM >$FILE
import { env } from "./src/utils/env-wrapper";
 
export default {
    type: "postgres",
    host: env.pg.host,
    port: env.pg.port,
    username: env.pg.username,
    password: env.pg.password,
    database: env.pg.database,
    synchronize: env.orm.synchronize,
    logging: env.orm.logging,
    dropSchema: false,
    entities: [
        "src/entities/**/*.ts"
    ],
    migrations: [
        "src/migration/**/*.ts"
    ],
    subscribers: [
        "src/subscriber/**/*.ts"
    ],
    cli: {
        "entitiesDir": "src/entities",
        "migrationsDir": "src/migration",
        "subscribersDir": "src/subscriber"
    }
}
EOM

FILE="./.env"

/bin/cat <<EOM >$FILE
# Server Properties
port=8080

# Database Properties
pg_host=localhost
pg_port=5432
pg_username=postgres
pg_password=root
pg_db_name=insert_name

# ORM Properties
orm_synchronize=true
orm_logging=true
EOM

FILE="./.gitignore"

/bin/cat <<EOM >$FILE
# Node artifact files
node_modules/
dist/

# Compiled Java class files
*.class

# Compiled Python bytecode
*.py[cod]

# Log files
*.log

# Package files
*.jar

# Maven
target/
dist/

# JetBrains IDE
.idea/

# Unit test reports
TEST*.xml

# Generated by MacOS
.DS_Store

# Generated by Windows
Thumbs.db

# Applications
*.app
*.exe
*.war

# Large media files
*.mp4
*.tiff
*.avi
*.flv
*.mov
*.wmv
EOM

FILE="./src/utils/env-wrapper.ts"

/bin/cat <<EOM >$FILE
class EnvWrapper {
 
    public port = this.getProperty("port");
 
    public pg = {
        host: this.getProperty("pg_host"),
        port: this.toNumber(this.getProperty("pg_port")),
        username: this.getProperty("pg_username"),
        password: this.getProperty("pg_password"),
        database: this.getProperty("pg_db_name"),
    }
 
    public orm = {
        synchronize: this.toBoolean(this.getProperty("orm_synchronize")),
        logging: this.toBoolean(this.getProperty("orm_logging"))
    }
 
    private getProperty(property: string): string {
        return process.env[property.toUpperCase()] || process.env[property.toLowerCase()] || "";
    }
 
    private toNumber(value: string): number {
        return +value;
    }
 
    private toBoolean(value: string): boolean {
        return value.toLowerCase() === "true";
    }
 
}
 
export const env = new EnvWrapper();
EOM

FILE="./tsconfig.json"

/bin/cat <<EOM >$FILE
{
  "compilerOptions": {

    "target": "es5",                          
    "module": "commonjs",                     
    "strict": true,                        
    "noImplicitAny": true,                 
    "strictNullChecks": true,              
    "strictFunctionTypes": true,           
    "strictBindCallApply": true,           
    "strictPropertyInitialization": true,  
    "noImplicitThis": true,                
    "alwaysStrict": true,                 
    "noUnusedLocals": true,                   
    "noUnusedParameters": true,                
    "esModuleInterop": true,                  
    "experimentalDecorators": true,        
    "skipLibCheck": true,                     
    "forceConsistentCasingInFileNames": true
    
  }
}
EOM

FILE="./src/app.ts"

/bin/cat <<EOM >$FILE
import express from "express";
import { json } from "body-parser";
import { sendInvalidMethodResponse } from "./utils/response-wrapper";

const app: express.Application = express();

app.use(json({ limit: "50mb", type: "application/json" }));

app.use(sendInvalidMethodResponse);

export default app;
EOM


FILE="./main.ts"

/bin/cat <<EOM >$FILE
import { env } from "./src/utils/env-wrapper";

import { createConnection } from "typeorm";
import { createServer } from "http";
import app from "./src/app";

(async function main(): Promise<void> {

    try {

        await createConnection();
        createServer(app).listen(env.port);
        
    } catch (error) {
        process.exit(-1);
    }
})();
EOM

npm install --save express body-parser pg typeorm reflect-metadata
npm install --save-dev typescript ts-node @types/node@10.17.51 @types/body-parser nodemon @types/express

git init
git add -A
git commit -m "Blinking Node - Initial Commit"

echo "Node initialized"

code .